spring:
  datasource:
    main:
      jdbc-url: jdbc:postgresql://localhost:5432/dataset?stringtype=unspecified
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver

    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver
    # osm数据暂时没用上
    osm:
      jdbc-url: jdbc:sqlite:D:\zhuomian\osm\2020-10-planet-14.mbtiles
      driver-class-name: org.sqlite.JDBC
    staticdb:
      jdbc-url: jdbc:sqlite:D:\zhuomian\水科院\python\data\static_database.db
      driver-class-name: org.sqlite.JDBC
    ship:
      jdbc-url: jdbc:sqlite:D:\zhuomian\水科院\python\data\ais.db
      driver-class-name: org.sqlite.JDBC
    monitor:
      jdbc-url: jdbc:sqlite:D:/zhuomian/monitor.db
      driver-class-name: org.sqlite.JDBC
    #配置druid连接池
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 5 #最小空闲连接数
      max-active: 20  #最大连接数
  #      web-stat-filter:
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
  #      stat-view-servlet: #访问监控网页的登录用户名和密码
  #        login-username: druid
  #        login-password: druid
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000ms
    #配置letture
    lettuce:
      pool:
        min-idle: 1 #最小空闲连接
        max-idle: 6 #最大空闲连接
        max-active: 10  #最大连接数
        max-wait: 1000ms  #最大阻塞时间
        shutdown-timeout: 200ms



  #mongodb地址
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/yangtze

#mybatis:
#  mapper-locations: classpath:mapper/*.xml

# 记得全局搜索，修改pythonStr，在TimedTask类、AnalyseUtil类有
pythondir:
  D:/zhuomian/水科院/python/


pictureAddress:
  E:/yangtze/other/picture/
visualAddress:
  E:/yangtze/other/visual/
tempAddress:
  E:/yangtze/other/temp/
basePath:
  E:/yangtze/user/
analyseAddress:
  E:/yangtze/other/analyse/
mapAddress:
  E:/yangtze/other/map/


resourcePath:
  E:/yangtze/resource/
modelPath:
  E:/yangtze/resource/models/


pgpath:
  D:/App/postgresql/bin/

#水情服务地址
waterLevelAddress:
  http://172.21.212.116:9999

#气象预警地址
meteorologyUrl:
  https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/
#AIS船舶地址
AISUrl:
  http://www.cjienc.cn/rest/es/queryBoxShip?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  http://www.cjienc.cn//rest/es/query/{0}/{1}?lx=acb&name={2}