spring:
  application:
    name: Yangtze
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8002

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: yangtze-secret #JWT加解密使用的密钥
  expiration: 345600 #JWT的超期限时间(60*60*24*4)
  failExpiration: 259200  #JWT彻底失效的时间,超期后再过3天(60*60*24*3)
  tokenHead: 'Bearer '  #JWT负载中拿到开头


encrypt:
  key: abcdef0123456789
